title: Speedboat
description: A post-Scrum operating model for AI-accelerated software teams
remote_theme: pages-themes/cayman@v0.2.0
show_downloads: false
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true