title: Speedboat
description: Start Less. Learn Faster. Land More.
remote_theme: pages-themes/cayman@v0.2.0
show_downloads: false
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
